spring:
  application:
    name: profile

  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/hms_profiledb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Custom application messages
USER_ALREADY_EXISTS: User with the given email already exists.
USER_NOT_FOUND: User with the given ID not found.
INVALID_CREDENTIALS: Invalid email or password.

# Server configuration
server:
  port: 8081
